-- Tạo database
USE master;
GO
DROP DATABASE IF EXISTS EmployeeManagement;
GO
GO
CREATE DATABASE EmployeeManagement;

USE EmployeeManagement;
-- Tạo bảng Department
DROP TABLE IF EXISTS Department;
CREATE TABLE Department (
  DepartmentID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY
 ,DepartmentName NVARCHAR(50) NOT NULL
 ,CreateDate DATETIME DEFAULT NULL
 ,CreateBy NVARCHAR(MAX) DEFAULT NULL
);

-- Tạo bảng Position
DROP TABLE IF EXISTS Position;
CREATE TABLE Position (
  PositionID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY
 ,PositionName NVARCHAR(50) NOT NULL
 ,CreateDate DATETIME DEFAULT NULL
 ,CreateBy NVARCHAR(MAX) DEFAULT NULL
);

-- Tạo bảng Employee
DROP TABLE IF EXISTS Employee;
CREATE TABLE Employee (
  EmployeeID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY
 ,EmployeeCode VARCHAR(10) NOT NULL UNIQUE
 ,EmployeeName NVARCHAR(50) NOT NULL
 ,MobilePhone VARCHAR(13) UNIQUE DEFAULT NULL
 ,Email VARCHAR(50) DEFAULT NULL
 ,Gender VARCHAR(10) DEFAULT NULL CHECK (Gender IN ('Male', 'Female', 'Other', NULL))
 ,DateOfBirth DATE DEFAULT NULL
 ,Salary DECIMAL(10, 4) DEFAULT NULL
 ,CreateDate DATETIME DEFAULT GETDATE()
 ,CreateBy NVARCHAR(MAX) DEFAULT NULL
 ,PositionID UNIQUEIDENTIFIER DEFAULT NULL
 ,DepartmentID UNIQUEIDENTIFIER DEFAULT NULL
 ,CONSTRAINT FK_EmployeePosition FOREIGN KEY (PositionID)
  REFERENCES Position (PositionID)
 ,CONSTRAINT FK_EmployeeDepartment FOREIGN KEY (DepartmentID)
  REFERENCES Department (DepartmentID)
 ,
);


--Tạo bảng Tài khoản
DROP TABLE IF EXISTS Account;
CREATE TABLE Account (
  AccountID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY
 ,Username VARCHAR(20) NOT NULL UNIQUE
 ,Password VARCHAR(20) NOT NULL
 ,EmployeeID UNIQUEIDENTIFIER NOT NULL
 ,CreateDate DATETIME DEFAULT NULL
 ,CreateBy NVARCHAR(MAX) DEFAULT NULL
 ,CONSTRAINT FK_AccountEmployee FOREIGN KEY (EmployeeID)
  REFERENCES Employee (EmployeeID)
);